[package]
name = "aestress"
version = "0.1.0"
authors = ["Hazel Victoria Campbell <github@orezpraw.com>"]
edition = "2018"

[dependencies]

[profile.dev]
opt-level = 3
lto = true
incremental = false
codegen-units = 1
